Models/AlunoModel.cs
using ProjetoTurma.Enum;
using System.ComponentModel.DataAnnotations;

namespace ProjetoTurma.Models
{
    public class AlunoModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Informe o Nome")]
        public string Nome { get; set; }

        [Required(ErrorMessage = "Informe o Email")]
        [EmailAddress(ErrorMessage = "Digiet o email corretamente")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Informe a Escola")]
        public string Escola { get; set; }

        [Required(ErrorMessage = "Informe o Curso")]
        public string Curso { get; set; }

        [Required(ErrorMessage = "Informe a Situação")]
        public SituacaoEnum Situacao { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace ProjetoTurma.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/AlunoController.cs
using Microsoft.AspNetCore.Mvc;
using ProjetoTurma.Models;
using ProjetoTurma.Repositorio.Interface;
using System.Collections.Generic;

namespace ProjetoTurma.Controllers
{
    public class AlunoController : Controller
    {
        private readonly IAlunoRepositorio _alunoRepositorio;

        public AlunoController(IAlunoRepositorio alunoRepositorio)
        {
            this._alunoRepositorio = alunoRepositorio;
        }

        public IActionResult Cadastrar()
        {
            return View();
        }

        public IActionResult ApagarConfirmacao(int id)
        {
            AlunoModel aluno = _alunoRepositorio.ListarPorId(id);
            return View(aluno);
        }

        [HttpPost]
        public IActionResult Cadastrar(AlunoModel aluno)
        {
            try
            {
                if(ModelState.IsValid)
                {
                    _alunoRepositorio.Adicionar(aluno);
                    TempData["MensagemSucesso"] = "Aluno e turma cadastrada com sucesso.";
                    return RedirectToAction("Consultar");
                }

                return View(aluno);
            }
            catch (System.Exception erro)
            {
                TempData["MensagemErro"] = $"Ops, não foi possivel cadastrar aluno e sua turma, tente novamente, erro: {erro.Message}";
                return RedirectToAction("Consultar");
            }
        }

        public IActionResult Consultar()
        {
            List<AlunoModel> listar = _alunoRepositorio.ListarTodosAlunos();
            return View(listar);
        }

        public IActionResult Editar(int id)
        {
            AlunoModel aluno = _alunoRepositorio.ListarPorId(id);
            return View(aluno);
        }

        [HttpPost]
        public IActionResult Alterar(AlunoModel aluno)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _alunoRepositorio.Atualizar(aluno);
                    TempData["MensagemSucesso"] = "Aluno e turma atualizado com sucesso.";
                    return RedirectToAction("Consultar");
                }
            }
            catch (System.Exception erro)
            {
                TempData["MensagemErro"] = $"Ops, não foi possivel atualizado aluno e sua turma, tente novamente, erro: {erro.Message}";
                return RedirectToAction("Consultar");
            }

            return View("Editar", aluno);
        }

        public IActionResult Apagar(int id)
        {
            try
            {
                bool apagado = _alunoRepositorio.Apagar(id);

                if(apagado)
                {
                    TempData["MensagemSucesso"] = "Aluno e turma atualizado com sucesso.";
                }
                else
                {
                    TempData["MensagemErro"] = "Aluno e turma não foi atualizado com sucesso.";
                }

                return RedirectToAction("Consultar");
            }
            catch (System.Exception erro)
            {
                TempData["MensagemErro"] = $"Ops, não foi possivel atualizado aluno e sua turma, tente novamente, erro: {erro.Message}";
                return RedirectToAction("Consultar");
            }
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ProjetoTurma.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ProjetoTurma.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Aluno/ApagarConfirmacao.cshtml
@model AlunoModel
@{
    ViewData["Title"] = "Apagar Aluno";
}

<div class="text-center">
    <h2 class="display-4">Confirmação da deleção do Aluno(@Model.Nome)?</h2>
</div>

<a role="button" asp-route-id="Id" asp-controller="Aluno" asp-action="Consultar" class="btn btn-danger btn-block">Voltar</a>
<a role="button" asp-route-id="Id" asp-controller="Aluno" asp-action="Apagar" class="btn btn-primary btn-block">Exclusão do aluno</a>

Views/Aluno/Cadastrar.cshtml
@using ProjetoTurma.Enum
@model AlunoModel
@{
    ViewData["Title"] = "Cadastro Aluno";
}

<div class="text-center">
    <h2 class="display-4">Cadastro de Aluno e Turma</h2>
</div>

<form asp-controller="Aluno" asp-action="Cadastrar">
  <div class="form-group">
    <label for="nome">Nome</label>
    <input type="text" asp-for="Nome" class="form-control" placeholder="Nome">
    @Html.ValidationMessageFor(x => x.Nome)
  </div>
  <div class="form-group">
    <label for="e-mail">E-mail</label>
    <input type="text" asp-for="Email" class="form-control" placeholder="Email">
    @Html.ValidationMessageFor(x => x.Email)
  </div>
  <div class="form-group">
    <label for="escola">Escola</label>
    <input type="text" asp-for="Escola" class="form-control" placeholder="Escola">
    @Html.ValidationMessageFor(x => x.Escola)
  </div>
   <div class="form-group">
    <label for="e-curso">Curso</label>
    <input type="text" asp-for="Curso" class="form-control" placeholder="Curso">
    @Html.ValidationMessageFor(x => x.Curso)
  </div>
  <div class="form-group">
    <label for="situação">Situação</label>
    <select class="form-control" asp-for="Situacao">
        <option value="0">Selecione</option>
        <option value="@SituacaoEnum.EmAndamento">Em andamento</option>
        <option value="@SituacaoEnum.Concluido">Concluído</option>
    </select>
    @Html.ValidationMessageFor(x => x.Situacao)
  </div>
  <button type="submit" class="btn btn-primary">Cadastro Aluno</button>
</form>

Views/Aluno/Consultar.cshtml
@model List<AlunoModel>
@{
    ViewData["Title"] = "Consultar Aluno";
}

<div class="text-center">
    <h2 class="display-4">Consultar Aluno</h2>
</div>

<br/>

  @if(TempData["MensagemSucesso"] != null)
    {
         <div class="alert alert-success" role="alert">
           <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
           @TempData["MensagemSucesso"]
        </div>   
    }

    @if(TempData["MensagemErro"] != null)
    {
         <div class="alert alert-success" role="alert">
           <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
           @TempData["MensagemErro"]
        </div>   
    }

<br/>

<table class="table table-striped" id="table-alunos">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nome</th>
      <th scope="col">E-mail</th>
      <th scope="col">Escola</th>
      <th scope="col">Curso</th>
      <th scope="col">Situação</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
        @if (Model != null && Model.Any())
        {
            foreach(var aluno in Model)
            {
                 <tr>
                  <th scope="row">@aluno.Id</th>
                  <td>@aluno.Nome</td>
                  <td>@aluno.Email</td>
                  <td>@aluno.Escola</td>
                  <td>@aluno.Curso</td>
                  <td>@aluno.Situacao</td>
                  <td>
                      <a role="button" asp-controller="Aluno" asp-route-id="@aluno.Id" asp-action="Editar" class="btn btn-primary">Editar</a>
                      <a role="button" asp-controller="Aluno" asp-route-id="@aluno.Id" asp-action="ApagarConfirmacao" class="btn btn-danger">Apagar</a>
                  </td>
                </tr> 
            }
        }
  </tbody>
</table>

Views/Aluno/Editar.cshtml
@using ProjetoTurma.Enum
@model AlunoModel
@{
    ViewData["Title"] = "Editar Aluno";
}

<div class="text-center">
    <h2 class="display-4">Cadastro de Aluno e Turma</h2>
</div>

<form asp-controller="Aluno" asp-action="Alterar" method="post">
  <input type="hidden" asp-for="Id" />
  <div class="form-group">
    <label for="nome">Nome</label>
    <input type="text" asp-for="Nome" class="form-control" placeholder="Nome">
    @Html.ValidationMessageFor(x => x.Nome)
  </div>
  <div class="form-group">
    <label for="e-mail">E-mail</label>
    <input type="text" asp-for="Email" class="form-control" placeholder="Email">
    @Html.ValidationMessageFor(x => x.Email)
  </div>
  <div class="form-group">
    <label for="escola">Escola</label>
    <input type="text" asp-for="Escola" class="form-control" placeholder="Escola">
    @Html.ValidationMessageFor(x => x.Escola)
  </div>
   <div class="form-group">
    <label for="e-curso">Curso</label>
    <input type="text" asp-for="Curso" class="form-control" placeholder="Curso">
    @Html.ValidationMessageFor(x => x.Curso)
  </div>
  <div class="form-group">
    <label for="situação">Situação</label>
    <select class="form-control" asp-for="Situacao">
        <option value="0">Selecione</option>
        <option value="@SituacaoEnum.EmAndamento">Em andamento</option>
        <option value="@SituacaoEnum.Concluido">Concluído</option>
    </select>
    @Html.ValidationMessageFor(x => x.Situacao)
  </div>
  <button type="submit" class="btn btn-primary btn-block">Cadastro Aluno</button>
</form>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Pagina Inicial";
}

<div class="text-center">
    <h1 class="display-4">Welcome do aluno com turma</h1>
    <p>Desenvolvimento de projeto com aluno e turma</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProjetoTurma</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="https://cdn.datatables.net/v/dt/dt-1.13.5/datatables.min.css" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Projetodon Aluno e Turma</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Aluno" asp-action="Cadastrar">Cadastro</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Aluno" asp-action="Consultar">Consulta</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Desemnvolvido por Gustavo Gregório
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/v/dt/dt-1.13.5/datatables.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>